[package]
name = "pdf_convert"
version = "0.1.0"
edition = "2024"

[dependencies]
pdfium-render = "0.8.33"
pdf-writer     = "0.13"
anyhow         = "1"          
clap           = { version = "4", features = ["derive"] } 