[package]
name = "pdf_convert"
version = "0.1.0"
edition = "2024"

[dependencies]
pdfium-render = "*"
krilla = "*"
pdf-writer = "*"
lopdf = "*"
anyhow = "*"
clap = { version = "*", features = ["derive"] }
rustybuzz = "0.10" 